version: '3.7'
services:
  crm-dashboard:
    ports:
      - 3000:80
    environment:
      - REACT_APP_API_URL=https://store.tst.qilin.super.com/api
      - REACT_APP_AUTH_URL=http://localhost:8082/v1/auth
      - REACT_APP_QILIN_SDK_INIT_URL=sdk/v1
